export const dateTypes = {
  SET_FIRST_DATE: 'SET_FIRST_DATE',
  SET_START_DATE_OF_WEEK: 'SET_START_DATE_OF_WEEK',
  SET_END_DATE_OF_WEEK: 'SET_END_DATE_OF_WEEK',
};

export const inputEventTypes = {
  SET_DATES_IS_CALLED: 'SET_DATES_IS_CALLED',
  DAY_IS_SELECTED: 'DAY_IS_SELECTED',
  DATE_IS_SELECTED: 'DATE_IS_SELECTED',
};

export const responseTypes = {
  STORE_EVENTS_DATA: 'STORE_EVENTS_DATA',
};

export const errorTypes = {
  STORE_EVENTS_DATA_ERROR: 'STORE_EVENTS_DATA_ERROR',
};
