export const dateTypes = {
  SET_FIRST_DATE: 'SET_FIRST_DATE',
  SET_START_DATE_OF_WEEK: 'SET_START_DATE_OF_WEEK',
  SET_END_DATE_OF_WEEK: 'SET_END_DATE_OF_WEEK',
};

export const actionTypes = {
  SET_DATES_IS_CALLED: 'SET_DATES_IS_CALLED',
  SET_DATES_BY_DAY_IS_CALLED: 'SET_DATES_BY_DAY_IS_CALLED'
};
