export const dateTypes = {
  SET_DATE_SELECTED: 'SET_DATE_SELECTED',
  SET_DAY_SELECTED: 'SET_DAY_SELECTED',
  SET_START_DATE_OF_WEEK: 'SET_START_DATE_OF_WEEK',
  SET_END_DATE_OF_WEEK: 'SET_END_DATE_OF_WEEK',
};

export const inputEventTypes = {
  SET_DATES_IS_CALLED: 'SET_DATES_IS_CALLED',
};

export const responseTypes = {
  STORE_EVENTS_DATA: 'STORE_EVENTS_DATA',
};

export const errorTypes = {
  STORE_EVENTS_DATA_ERROR: 'STORE_EVENTS_DATA_ERROR',
};
